### ISSUE TITLE
[very critical bug]can't use terminal.

### ISSUE THREAD

**Issue by drink1101** [Wet-Boys/LethalEmotesAPI#81] opened 2024-01-11 21:06 UTC
**Describe the bug**
So if you start the game create a new file everything is fine, but if you create another file, the terminal started bugged out the menu will just stay on the game's monitor not your montior and once you press TAB to quit the terminal you can't use it anymore.you can only close the game and open it again.
I'm pretty sure this mod is causing the bug. [BepInExPack, LethalCompany_InputUtils, LethalConfig, LethalEmotesAPI], ive tried enabled these mods one by one and the first three mods is fine but once I enable this mod the terminal start bugged out

**To Reproduce**
1. open the game 
2. Click on HOST, CONFIRM, go to use the terminal the first time is normal.
3. then press ESC click QUIT create another save or just use the last one.
4. after you spawn go to use terminal and you can see error

**Expected behavior**
just hope it can be fixed ASAP😭

**Screenshots**
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/85337928/ab6d2318-8d8f-43fd-a1b9-a9742f9a85ce)
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/85337928/1d8330f4-4022-4c3a-bea6-ffb37b4a1c59)
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/85337928/ea7bbc6e-7933-411f-95c3-587a3b4161e5)
after quit the terminal, you can't use it anymore

**Logs**
Please attach any relevant logs, this makes it far easier for us to fix your issue.
Finding Logs (r2modman):
1. Go to your profile in r2modman.
2. Click `Settings>Locations>Browse profile folder`
3. Open the `BepInEx` folder
4. The log file we want is called `Lo
[LogOutput.log](https://github.com/Wet-Boys/LethalEmotesAPI/files/13908306/LogOutput.log)
gOutput.log`

**ModPack Code**
Having a ModPack code also makes it easier for us to test for the issue.
I only have [BepInExPack, LethalCompany_InputUtils, LethalConfig, LethalEmotesAPI], these mods enabled cause they are this mod's Dependencies.
if you need this is the code:  018cfa58-77a5-e863-5249-dec94d2ca18b

**Additional context**

**Comment by Rune580** [comment] 2024-01-11 21:10
duplicate of #77, but leaving up for visibility

**Comment by ToastedOven** [comment] 2024-01-11 21:32
Yeah this was a very shortsighted mistake I made, was trying to clean up objects we spawned but I didn't do it properly. It's working on my branch, once I get through a few more bug reports it should get pushed out (aka sometime tonight)

**Comment by drink1101** [comment] 2024-01-11 22:28
also i just found out that you can't see items when you pick them up and if you drop them, they will just go some random unkonwn places, and hand model will stuck 
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/85337928/50cec3e3-fc30-4c09-a93d-cc3662b5f9a8)
![image](https://github.com/Wet-Boys/LethalEmotesAPI/assets/85337928/c70cd5a5-6963-463d-aa00-8f10b81b76d7)

**Closed** 2024-01-12 02:14 UTC
Labels: bug, duplicate
