### ISSUE TITLE
LethalEmotesAPI causing errors after second opening of a world.

### ISSUE THREAD

**Issue by Vexxingfr** [Wet-Boys/LethalEmotesAPI#77] opened 2024-01-11 08:34 UTC
I'm not sure this has been documented yet, but I couldn't find a single hint of it through looking through this github and searches online. There seems to be an error with the LethalEmotesAPI v1.1.11 where if you are to exit to menu and reopen a run or a session, the entire session breaks making it so that items don't appear and hand and disappear into the void after being dropped as well as not allowing the use of the terminal and its function. The first time opening a lobby seems to work fine so I am not sure how much of a problem it is for the developer at this current moment but it causes for some really bad hiccups with people on unstable connections. This was tested using only the mod and its necessities downloaded so it is not of an problems with mod interference. If this issue is solvable thank you for taking the time of your day to fix this error!

![image_2024-01-11_002701883](https://github.com/Wet-Boys/LethalEmotesAPI/assets/156297215/a6502e1a-693b-4000-9608-6f2782458ec3)
This is the list tested and I am uploading a video in order to show the issue at hand.

**Comment by Vexxingfr** [comment] 2024-01-11 08:38
https://youtu.be/yrSjp86JPYM
Heres a follow up video on the issue using those same few mods with no other interference. I have tested base game and my modpack without the LethalEmotesAPI and it worked perfectly fine so its the only conclusion that I could come up with my hour to two hours of testing mods one by one.

**Comment by Rune580** [comment] 2024-01-11 14:43
interesting, do you also happen to have the logs?

**Comment by HamedAlmanthari** [comment] 2024-01-11 15:45
omg i was trying to find out which mod was causing this from over 100 mods that i have lmao. i just found out and was going to open an issue. this mod also happens to cause alot of performance loss, i'm not sure why.

**Comment by HamedAlmanthari** [comment] 2024-01-11 15:50
also, after rehosting, when you pick up stuff and throw them, they disappear or get thrown outside of the ship. and also, it glitches when you interact with the terminal after rehosting.

**Comment by Rune580** [comment] 2024-01-11 16:02
> omg i was trying to find out which mod was causing this from over 100 mods that i have lmao. i just found out and was going to open an issue. this mod also happens to cause alot of performance loss, i'm not sure why.

Could you provide a modpack code, so that we can do some performance profiling

**Comment by HamedAlmanthari** [comment] 2024-01-11 16:57
nevermind about the performance loss 💀 i thought because i disabled this mod i got more fps but that was not the case. sorry for the misinformation.

**Comment by HamedAlmanthari** [comment] 2024-01-11 17:20
the rest still happens tho.

**Comment by Rune580** [comment] 2024-01-11 17:49
See where the issue is, marking this as a confirmed bug. We'll look into it as soon as we can

**Comment by Vexxingfr** [comment] 2024-01-11 20:51
Thank you for providing the information for me, I was asleep and the issue is getting looked into faster because of you @HamedAlmanthari :3

**Comment by Rune580** [comment] 2024-01-11 20:53
Comparing this to an older issue we had, this seems to be a regression of #44

**Comment by Vexxingfr** [comment] 2024-01-11 21:02
yeah seems to be the sameish issue, thank you for putting the time and effort to fix the issue! Was very sad to not be able to use this mod for a bit but hopefully it gets resolved soon. ty i love you :3333

**Comment by HamedAlmanthari** [comment] 2024-01-11 21:04
i'm still using this mod i don't care because it's so good 💀

**Comment by ToastedOven** [comment] 2024-01-11 21:32
Yeah this was a very shortsighted mistake I made, was trying to clean up objects we spawned but I didn't do it properly. It's working on my branch, once I get through a few more bug reports it should get pushed out (aka sometime tonight)

**Comment by Vexxingfr** [comment] 2024-01-11 21:47
nice thank you for everything, we host sessions friday so having this fixed is really cool thank you!

**Closed** 2024-01-12 02:14 UTC
Labels: bug
